name: Deploy to DigitalOcean Kubernetes

on:
  release:
    types: [created]

env:
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ env.KUBECONFIG }}

      - name: Deploy to Kubernetes
        run: |
          kubectl create secret docker-registry dockerhub-credentials \
            --docker-server=https://docker.io \
            --docker-username=${{ secrets.DOCKER_HUB_USERNAME }} \
            --docker-password=${{ secrets.DOCKER_HUB_TOKEN }} \
            --docker-email=${{ secrets.DOCKER_HUB_EMAIL }} \
            --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f ./manifests/deployment.yaml
          kubectl apply -f ./manifests/service.yaml
          